apiVersion: primehub.io/v1alpha1
kind: PhAppTemplate
metadata:
  name: filebrowser
  namespace: hub
  annotations:
    helm.sh/hook: post-install, post-upgrade
spec:
  name: File Browser
  version: v2.30.0
  description: File Browser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files. It allows the creation of multiple users and each user can have its own directory. It can be used as a standalone app.
  docLink: https://filebrowser.org/
  icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAJTklEQVR4nMRae2xT1xn/nevrGz8SO7GTEOdJwiuEJqwQlvIojyE6YBrZ1pG2jFFUukqDSZ20FkYHQ1rX0ZL9M2l0UgUVUI12aN3EaAWrSoFUTQo0pSGQBwohxHmAHSd24lfs2Lc6N9z43tiJHwn0J1ny/e53zv19537nnO9832UxDUjKWFioKVi5Rp21pJwzzpuv1M8sUGgzMwigpvd5wBNwWax+R8ddn6212XPvar37bs2FYWtD+1SfTRJtqEjOTktbvGuHvmTLNi51ZmkiffjsHTccN0+eGPj68JGAs2cgkT7iNoAzlOSlL39td0rx09sZVpWcyEPHIzjidQ61fHisr/Yv1T5bU2c8bWM2gOFSVOkrX99rWLzrVcKw6mj6SgWg4Ub/u32APxD9GXxwxDNQf7jaWnPgYNDn8MbCKyYD1DlLS3MqT51S6nOLI91XMEBFEbB0NlCWC8yeAejVPMiD3nkecHgI2u4DjV1AbRtwpR0YCUZ+nt/R1dJ1uqrK213XOGUD9GUv/My0/h/HiYILc5dZGcAzFcDGMiBNy0frSoYBF8HZRuCDy8BtS/h9PuBz9p779fOO6+/+Z7J+FBPfIkhf9earWT849A5hFEnSOzlpwP5NwP5KYGEeDzUXF3cBtE1pLh0AgqJ0oKkHGJI4DWEUXPLcys2EVXvcHedr4zYgfdWbr2Qs21MNIn9Lz1YAf98KlGSHXGQqoH3MyQI2LyEY8gA3uiX3AKLJW7GOsCq3u+PTiEZENIC6DR15KXmOBV7/KfDSah7sJO8tUdA+V84D8gwEn98CApL5oc5bsdY/aL4xfP9a8/h2YWNIJ2zBLy7WSn0+VQO8/UtgYX58fp4oGswEO08AdndIRufE3X+uXuYZN7EZ2QWnV9HVRkqejvyjJE9B5xV9JieJEyinnJ+cOkU4vUqqK3OGjDVv7U8ueuppqYy6zariR0deRJYeMKUSnG8KyRRJunSiVAdd7ecuirKQjxtK8op+1dAq3aSeqwD2bQonv+sb4LZb7n3m+loM3TPjT1t/iBxj6qTk+nzA8U6AI8COgiB+bAKYCVaEP/+P4P3LoWu62bUfWTjPZ2syQ+pCxuV7d0vJ06XylQ2RCbQ4CbwBYFs+sNwAdHuBbrsLXVY7+GAQLIOw37uffCn86H86JLTNHQ+wr4XBzgag1xP5LVMOlIsIytG4bO9u8VowgAZmuuKfb5c2fHkdoFJO7Do7C4EtuTz2F/OYq51QbQzn6luFXyR80c9gWz0QCITHG5TDb9fJZbriqu2U85gBaYt27pAGZrMygQ1lkxO65RoNEfp9BDZfdAOiwRvg0We1gufDB2192eiuL4JhuWTKecwA/YIt26QNnvk+9cnJJ+6/uoH1dQQb6gCbf+oGCEZ4vRh0OMLklAsNWaQQOTP0MMKlFo7F8zQwizb6Inq8gDuGKJOiYm6+8IsGu90Oj8cTJqecFJJFn3Km3FlN/so1sgcVAYY4A7NYsGfzmph1rRYLTCYTlFwoyKKcKoqIEMmKoNwZlam8XNqYhsTfNeg8sNL5EJTH20tnyfVUpvLFbJKxZL5USOP5RJCclQtFkgrfuJNg7ptc1zESvT+/34/+/n4Y09ND3PLkOknG4vmsUp9fIBXSFSgRpM2aD7qufTYEYCixPsbD6XSC4zik6HTCddE4bkrdzJmMQpM5ZiI9BqZqHn3YMBnoW6CrE0Wahhc2QhEKbWY6AwKNKKBn2OmI8acbdH+gmxzlppUdraBhvjNWcYCSn2iTY8HDDYIUPMgeUJ1Y38L6TGCFcWrk/m8BPrdF16NuZB8YgGtY9kA3G3Bb+lhtpmCAP0APESTmA3oKC/jcLtzsvJcQ+e/NykEyq4pZ33zfiZFgyACBu9/ReZfVZhaKwjYLsKQwdhIalRIFmWlx0A5BpYwvs9lpV8qufY6ODnbY1tSkzi5fLQobu+I0IInDzBmGuIgkilaLfAb7bC3NrLf3q3qUhmK5ujbghSdj77S3fxBXbpkTIvTkAjpSmpj1r3XLE4KUO+vqrLkgFV5uB/pdJOZ4yGTQofKJBTGTCIM7NjWHh8H1Hrmx7s6aC4zP2nDHZ78zdtIPBIGz1xPn87BwqV2LgGRMKedha8MdYRY5bp48kbH8D9XizQ+uAM89QaKeCSjMVjs+u96WEKmN5cU0ioqqF+SBj5t0MhnlDGEfADDw9dtHjRW/OyCeytoto2/hRwujk8jLSMXza8sTMkBADDnomtsamO2h0Do44nVSzmMGBJw9A4Mt/z6W+tjW34hKf/sEWFtCIp6L6fpfqgP+W9eIM9a40vlh8GfPwcbH5+KqLfLbHh4Bjl+Vr3KUq1gQGVuI+744eEhf8uwOMTPRbQf+ehbYtym8Uz3xoXOIh1+VAqcue0oGqDkN2h3DMCDyufTolwbcd4bWfz444rHVHjwkXo8Z4O9vMvfXH642Lnn5j6Ls/ctAaS5B5SL56BxdBPT23kMwh8onzwFFByXeE/HO+VtafNSsl8koRzEnhPG5UYZLURW92HRNWsjgFMCxF8NTi263Wzj6PSy0WDjs+cgEfyAUb/ocXS13jjz2uLR6I4tGg74hb/fpqio+4HOONQoAO98DGjrlEZ5Go0FKSsrDIX+fw4FzWTLylFPP6aqq8aWnsET5yFCXxT/U05oyp3KzmF73+oEzDYBJT1BsCumq1GohSoyUkEoU1G3eOJ8Fj19CHgj2nn1pi7PtzKXx+hEz/UIenlW7tXkrnhJldIM73zy6S1cUESGfTwiBWqOB0+WKGKvHg+ERgnfqDDj+lRFBXv62bXVv7em/XH00UrsJSxVCWUehokaslc6VG93Axw2AQUswewaBgiHCudXlciVEnG5Sl25r8canmbjWLQ8V6MhT8taLe6snaj+lIl9RxmjJSUg6+QeEpFSsoLFNTbtW2GE77eFFtliLfNNaZp1vHMC8DA/yUv3QqYKyMuugl4HZrkSLJUmIKmlgFpjA6/yOrha6mIyvxiRsAEKF7t8bFu/aHUuhm2UAtXJ0cnv8iglrwlLQTYqu833TXeiWgjOW5BmXvbZbN82fGgy2fHjM9jA/NRiPafnYw9HR6Lhx8r1H+rFHJCRllBVq8letUWcvKecMDz630WSmkwc5Jx5wB1yWPuFzm/7WZk/v1Xr33UsXhq3Xp/y5zbcBAAD//0D2qB/l6mzzAAAAAElFTkSuQmCC
  defaultEnvs:
  - name: FB_BASEURL
    description: "File Browser app base url"
    defaultValue: $(PRIMEHUB_APP_BASE_URL)
    optional: false
  - name: FB_ROOT
    description: "File Browser root to prepend to relative paths"
    defaultValue: $(PRIMEHUB_APP_ROOT)
    optional: false
  - name: FB_USERNAME
    description: "File Browser login username"
    defaultValue: "phuser"
    optional: false
  - name: FB_PASSWORD
    description: "File Browser login password, the default value here is 'password', you can update it with any bcrypt hashed string"
    defaultValue: "$2y$10$EGoZFg7FXT.saIZ0DqD5iOZQz2zvL6mZa3faMCZtzTFK2a8F50iie"
    optional: false
  template:
    spec:
      podTemplate:
        spec:
          containers:
          - name: filebrowser
            image: filebrowser/filebrowser:v2.30.0
            ports:
            - containerPort: 80
              name: http
              protocol: TCP
      svcTemplate:
        spec:
          ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: 80
      httpPort: 80