apiVersion: primehub.io/v1alpha1
kind: PhAppTemplate
metadata:
  name: sqlpad
  namespace: hub
  annotations:
    helm.sh/hook: post-install, post-upgrade
spec:
  name: sqlpad
  version: v7.4.4
  description: SQLPad is a web app for writing and running SQL queries and visualizing the results. Supports Postgres, MySQL, SQL Server, ClickHouse, Crate, Vertica, Trino, Presto, Pinot, Drill, SAP HANA, BigQuery, SQLite, TiDB and many others via ODBC.
  docLink: https://getsqlpad.com/en/introduction/
  icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAe1BMVEUAAAD////U1NTDw8M/Pz/4+PhgYGDl5eXo6Oh5eXnz8/PPz8/v7++qqqq/v7/5+fmLi4tOTk51dXUgICDIyMixsbHe3t6BgYGNjY01NTUuLi4lJSVra2tmZmaTk5NVVVUODg4WFha3t7dHR0ebm5tCQkIbGxtaWlo5OTnx0wvEAAAGEElEQVR4nO2c6XqyOhRGQYsj1KEIdahFa4f7v8Kj/U7tzkhCDI087/qrkCyG7LCzIYoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA0Di8756P/Xza603z/qp83Rhut37Q87XebCufHTdjkBVpzFFkLyabFvx2IsmoKPrPu61vCyWL40TRtcljvWSv3vBHdJgtWtAR2A213UrnNdubG14YPbciRXipv8iSvXYPdobn6+LUkto/jmYHfqzZha3heXdG9/dNeBNGFxXT6oaGcfzYkuDSplPLWxrGo3UbgmO7TmW3NIyTt78QHOXHfblblvusP5Vcv4pLq5lhnLz7FnzgWkz37CTmqezzncpvaRjPfBuyUTCVjpbzEdsp6VkkhtPXgciunJ9WhWRO0fMreGIaW6n+9sx2ShauiWFf3V41yLjDFcdeA+MH05Rm2rKhF2F6kPzDzPDCmL+5fQ6oTKRXBoJvVr9/lM4qzQ2jKGMN5Tf2TdjOLC6Wvf5U2xhGL6ziQ4O+m7EnrRS1/z5p+29lGL0zQ46/uQ29uQweaL7/Pqnfl4FhtGBOYmXeZys2SYNeqSK0pSE706h7NGvKK2ljZ7JBoemLrSFzAfmKieVvE5Mnkw0yTeetDelsKvGU2SCxYmi0wULzN2vDaEoUPT0qkhmne0iyN9wRQ0/zmvy3Bffx2t7wiUQMT0F/at0pDfaGdBNPQw05h/Xxvo4GhmTyNnJuX0r/li00MKRjuWwy7w45hmbRQkcDQ5IgSpzbr2sh/nTdmZth7CcgvpEWlA+/pgR5DivyuJ243ghuhp7uQzqYKrOEpriNNJ7GUtpEHL+67cstWrhHKzkVfQ5N3NIlbhF/6tS2BpJ8OV8pTuOZ26zNW77tiRrGqctZtDcckKb1WTAXuKyX0XOwHLenJ3+5qIpLQjcPi9aGX6RZs8fTZnB5vXg0aLgja0N6Cl1DlRbuOj0Pa1+N9mNryESqpofVjJxXjB+bjDiWhp/MhdOgvYZ9++Fov3BpZ/hKs+3ekolXprzgmdx2imNlOGfaSpt124ZHiWI8tDuyFoYLrrTFIUYZwy4j/jBbWdQumRpulvxd4Z4jMuFFUfBV6EpoGEi/VYm79aDMioRvQroa6YGDOKT+w7R2iZ6ZRMZsJm+gvRq3nbJuaGUyp2paqdBeYdSZTHGUzyNr/YFuaNjGKEPYqOvb8rqZTiPDmXMCzJovaeD4pmZS3sSw19Igw7JdCaPdzwEvddvZG6ba/fnkaa4qNp1qir4Dry/lWSgu1pn6WdzOsCir9mwUnORzAOXdaFHnnc+rFkU0lEJ91gXVSh8xTIZyiqKfzZemrze0wlhW3V5fT9NW6e9NkFW4ywUa5EsDYSleq9Ki/fs1jKK9MJmTZQDu2TDa8rFDtspw14ZR9MmFDslT450b8rkcSXLs7g3ZRRxJgvP+DdlcjhgxOmDIZOTEy7QLhhFNcwiJjU4Y0qUGIfvQCcNIt2jbDUOSxhGGmm4Yktp+4SGqG4Zk5V0onuiGIVmYFgpCu2F46Pw5jDp/H241Ft0wJOWaQs4tVMOTVeEFWZwWEqeBGm7sSubI3Pte5qW5VYH34XdFI634H8M0vERwi+URcpHey/PhJRlqUa1D8ori+kWQhqV8VFRBZqXJh/BrkIb/31b6r7JcoW8rSo5KiIbXmj2jdYYNTShKVlcCNNz8dmlUX4iwpikMmUKAhsz3Lo6V/s8DZulbNk0Iz5BWWV846aoG2CJUab1reIZCQWKSqQqDSraWSF6mFZ7hWrLC25uLM5ztia+VktfAhGcYVdLPl6XH+eL63sV2J36JRPphkyhIQ91n8tLRsBiOpEVgqglCkIZiFXs9JrUYARkyL4wboZ7/BGoYfchqvJXMNMXfoRpG0dL4c3RxriuFCdcwqhTVTzwTfUF0wIZn5vWOs7pCu7ANz3O4R61kUf9mAgk9Hr/75MJhlxXSADjpPZsUm7+Mr/h9i8mJzaI89nvXoWdS5Mfxm5/3yP+cqvrrHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiF/wDusj5DgZ6szAAAAABJRU5ErkJggg==
  defaultEnvs:
  - name: SQLPAD_ADMIN
    description: "Email address to give admin permissions to"
    defaultValue: sqlpad_admin@infuseai.io
    optional: false
  - name: SQLPAD_ADMIN_PASSWORD
    description: "Password to set for admin email address on application start. Requires `admin` setting to also be provided"
    defaultValue: sqlpad_password
    optional: false
  template:
    spec:
      podTemplate:
        spec:
          containers:
          - name: sqlpad
            image: sqlpad/sqlpad:7.4.4
            command:
            - bash
            - -c
            args:
            - export SQLPAD_BASE_URL=$(PRIMEHUB_APP_BASE_URL);
              /docker-entrypoint
            ports:
            - containerPort: 3000
              name: http
              protocol: TCP
      svcTemplate:
        spec:
          ports:
          - name: http
            port: 3000
            protocol: TCP
            targetPort: 3000
      httpPort: 3000